name: Firefox Reproduce Test
on:
  push:

jobs:
  publish:
    name: Test that docker can produce the same result for firefox
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.TOKEN }}
      - run: sudo apt-get update && sudo apt-get install curl ca-certificates gnupg lsb-release apt-transport-https
      - run: sudo sh -c "echo 'deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main' >> /etc/apt/sources.list"
      - run: wget -qO - 'https://gitsecret.jfrog.io/artifactory/api/gpg/key/public' | sudo apt-key add -
      - run: sudo apt-get install git-secret
      - run: printf $GPG_KEY | base64 --decode > private.key
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
      - run: gpg --import --no-tty --batch --yes ./private.key
      - run: git-secret reveal -f -p $GPG_PASSPHRASE
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - run: sudo mkdir -p /etc/apt/keyrings
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      - run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - run: sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io
      - run: docker build -f ./docker/Dockerfile -t builder .
      - run: docker run -v $(pwd):/data builder
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - run: npm install --global yarn
      - run: sudo apt-get update
      - run: sudo apt-get install libusb-1.0-0-dev
      - run: curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.3/protoc-21.3-linux-x86_64.zip
      - run: unzip protoc-21.3-linux-x86_64.zip -d $HOME/protoc && echo $HOME/protoc/bin >> $GITHUB_PATH
      - run: cd packages/extension/src/keplr-torus-signin && yarn install --frozen-lockfile
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: npx zx ./scripts/firefox-distribution-diff-check.mjs
